/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.0.13
 * Generated at: 2023-07-31 21:29:16 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class addbatch_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "adminheader.jsp", out, false);
      out.write("\n");
      out.write("<div class=\"mycontainer\">\n");
      out.write("	<div align=\"center\">\n");
      out.write("	<br>\n");
      out.write("	<h3>ADD NEW BATCH</h3>\n");
      out.write("	<br>\n");
      out.write("	<br>\n");
      out.write("\n");
      out.write("	<div>\n");
      out.write("		<table class=\"formtable\">\n");
      out.write("			<tr>\n");
      out.write("				<td style=\"padding: 10px;\">\n");
      out.write("					<div class='center'>\n");
      out.write("						<form style=\"width: 100%;\" action=\"Admin\" method = \"POST\">\n");
      out.write("						    <h2>Create Batch</h2>\n");
      out.write("						    <input type=\"hidden\" name=\"htmlFormName\" value=\"AddBatch\" />\n");
      out.write("						    <div>\n");
      out.write("						        <p>\n");
      out.write("							        <div class='right'>\n");
      out.write("							            <label for=\"name\">Batch Name:</label>\n");
      out.write("							            <input type=\"text\" id=\"name\" name=\"name\">\n");
      out.write("							        </div>\n");
      out.write("						        </p>\n");
      out.write("						    </div>\n");
      out.write("						    \n");
      out.write("						    <div>\n");
      out.write("						        <p>\n");
      out.write("							        <div class='right input-group date'>\n");
      out.write("							            <label for=\"stime\">Start Time:</label>\n");
      out.write("										<input id=\"startDate\" class=\"form-control\" type=\"time\" id=\"stime\" name=\"stime\">\n");
      out.write("							        </div>\n");
      out.write("						        </p>\n");
      out.write("						    </div>\n");
      out.write("						    \n");
      out.write("						    \n");
      out.write("						    <div>\n");
      out.write("						        <p>\n");
      out.write("							        <div class='right input-group date'>\n");
      out.write("							            <label for=\"etime\">End Time:</label>\n");
      out.write("							            <input id=\"startDate\" class=\"form-control\" type=\"time\" id=\"etime\" name=\"etime\">\n");
      out.write("							        </div>\n");
      out.write("						        </p>\n");
      out.write("						    </div>\n");
      out.write("						    \n");
      out.write("						    <div>\n");
      out.write("						        <p>\n");
      out.write("							        <div style=\"padding-left:20px;\">\n");
      out.write("							        	<Table width=\"100%\">\n");
      out.write("							        		<tr>\n");
      out.write("							        			<td>M</td>\n");
      out.write("							        			<td>Tu</td>\n");
      out.write("							        			<td>W</td>\n");
      out.write("							        			<td>Th</td>\n");
      out.write("							        			<td>F</td>\n");
      out.write("							        			<td>S</td>\n");
      out.write("							        			<td>Su</td>\n");
      out.write("							        		</tr>\n");
      out.write("							        		<tr>\n");
      out.write("							        			<td>\n");
      out.write("										            <input type=\"checkbox\" id=\"M\" name=\"M\" value=\"M\">\n");
      out.write("							        			</td>\n");
      out.write("							        			<td>\n");
      out.write("										            <input type=\"checkbox\" id=\"Tu\" name=\"Tt\" value=\"Tu\">\n");
      out.write("							        			</td>\n");
      out.write("							        			<td>\n");
      out.write("										            <input type=\"checkbox\" id=\"W\" name=\"W\" value=\"W\">\n");
      out.write("							        			</td>\n");
      out.write("							        			<td>\n");
      out.write("										            <input type=\"checkbox\" id=\"Th\" name=\"Th\" value=\"Th\">\n");
      out.write("							        			</td>\n");
      out.write("							        			<td>\n");
      out.write("										            <input type=\"checkbox\" id=\"F\" name=\"F\" value=\"F\">\n");
      out.write("							        			</td>\n");
      out.write("							        			<td>\n");
      out.write("										            <input type=\"checkbox\" id=\"S\" name=\"S\" value=\"S\">\n");
      out.write("							        			</td>\n");
      out.write("							        			<td>\n");
      out.write("										            <input type=\"checkbox\" id=\"Su\" name=\"Su\" value=\"Su\">\n");
      out.write("							        			</td>\n");
      out.write("							        		</tr>\n");
      out.write("							        	</Table>\n");
      out.write("							            \n");
      out.write("							        </div>\n");
      out.write("						        </p>\n");
      out.write("						    </div>\n");
      out.write("						    \n");
      out.write("						    <div>\n");
      out.write("						        <p>\n");
      out.write("							        <div class='right'>\n");
      out.write("							            <label for=\"capacity\">Capacity:</label>\n");
      out.write("							            <input type=\"number\" id=\"capacity\" name=\"capacity\">\n");
      out.write("							        </div>\n");
      out.write("						        </p>\n");
      out.write("						    </div>\n");
      out.write("						    \n");
      out.write("						    <div>\n");
      out.write("						        <p>\n");
      out.write("							        <div class='right'>\n");
      out.write("							            <label for=\"description\">Description:</label>\n");
      out.write("							            <input type=\"text\" id=\"description\" name=\"description\">\n");
      out.write("							        </div>\n");
      out.write("						        </p>\n");
      out.write("						    </div>\n");
      out.write("						    <div>\n");
      out.write(" 						        <p>\n");
      out.write("						            <button type=\"submit\" value=\"Submit\">Submit</button>\n");
      out.write("						            <button type=\"reset\" value=\"Reset\">Reset</button>\n");
      out.write("						        </p>\n");
      out.write("						    </div>\n");
      out.write("						</form>\n");
      out.write("					</div>				\n");
      out.write("				</td>\n");
      out.write("			</tr>\n");
      out.write("		</table>\n");
      out.write("		<br>\n");
      out.write("		<div class=\"emsg\">\n");
      out.write("			<p>\n");
      out.write("				");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${batcherrorMessage}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\n");
      out.write("			</p>\n");
      out.write("		</div>\n");
      out.write("	</div>\n");
      out.write("</div>\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "footer.jsp", out, false);
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
